name: Install pip package

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch

jobs:
  install-pip-package:
    runs-on: ubuntu-latest  # You can change the OS if needed (e.g., windows-latest)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the version of Python, e.g., '3.8'

      - name: Install requests package using custom action
        uses: durandtibo/pip-install-package-action@v0.3.1
        with:
          package-name: requests  # Specify the package you want to install (not 'pip')
          package-version: 'latest'  # You can specify a version (e.g., '2.25.0') or 'latest'
          python-version: '3.8'  # Ensure this matches the Python version used earlier

      - name: Verify package installation
        run: |
          pip show requests  # Verify the 'requests' package is installed
          pip --version  # Check the installed pip version
