vikranth - name: pip-install-package
  # You may pin to the exact commit or the version.
  # uses: durandtibo/pip-install-package-action@9bad1fbf91b61c40b8f555f0bb19f2e742a6f0b7
  uses: durandtibo/pip-install-package-action@v0.3.1
  with:
    # The package name
    package-name: 
    # The package target version
    package-version: 
    # The python version
    python-version: 
          
